#! /bin/sh

xsetroot -bg "#000000"

source ~/.dotfiles/scheme

bspc config normal_border_color $black1
bspc config focused_border_color $black2

sxhkd &
light-locker --no-late-locking &

picom -b

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config focus_follows_pointer true

bspc config border_width            1
bspc config window_gap              10 
bspc config -m "^1" top_padding     35

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

bspc rule -a \* state=pseudo_tiled
bspc rule -a Zathura state=tiled

bspc rule -a Inkscape state=floating center=on
bspc rule -a Gcr-prompter state=floating
bspc rule -a dmenu state=floating center=on private=on layer=above

bspc rule -a firefox:\* rectangle=1000x800+460+140

xsetroot -cursor_name left_ptr &

~/.dotfiles/wmstuff
