#! /bin/bash
#
# bt.sh
# Copyright (C) 2020 kenzie <kenzie@willowroot>
#
# Distributed under terms of the MIT license.
#


source $HOME/.dotfiles/scheme
disconnected=$cyan1
connected=$green1
off=$red1

status="$(bluetoothctl show | grep 'Powered: *' | sed 's/\W*Powered:\W//')"

prefix='%{T2}z%{T3}        %{T-}'

if [[ $status == 'yes' ]]
then
    conn="$(bluetoothctl info | grep 'Name:*' | sed 's/\W*Name:\W//' | head -1)"

    if [[ $conn == '' ]]
    then
        if [[ $1 == 'status' ]]
        then
            echo 0
        else
            echo "%{A1:bluetoothctl power off:}%{F$blue1}$prefix%{F-}  Not connected%{A}"
        fi
    else
        if [[ $1 == 'status' ]]
        then
            echo 1
        else
            echo "%{A1:bluetoothctl power off:}%{F$green1}$prefix%{F-}  $conn%{A}"
        fi
    fi
else
    if [[ $1 == 'status' ]]
    then
        echo -1
    else
        echo "%{A1:bluetoothctl power on:}%{F$red1}$prefix%{F-}  Disabled%{A}"
    fi
fi
