#! /bin/sh

# dmenu_run -b -nb '#2a2c3b' -sb '#008080' -sf '#2a2c3b' -nf '#918B88' -fn '-*-profont-medium-r-normal--10-100-72-72-c-50-iso8859-1'
FG=`cat ~/.dotfiles/scheme | grep -o "fore=#[0-9a-z]*" | sed "s/fore=//"`
BG=`cat ~/.dotfiles/scheme | grep -o "back=#[0-9a-z]*" | sed "s/back=//"`
FONT='Gohu GohuFont-14'
# dmenu_run -b -nb $BG -sb $HL -sf $BG -nf $FG -fn '-*-profont-medium-r-normal--10-100-72-72-c-50-iso8859-1'
dmenu_run -b -nb $BG -sb $FG -sf $BG -nf $FG -fn "$FONT"
