#!/bin/bash

track="$(mpc --format %id% current)"

if [[ $track != "" ]] 
then
    ffmpeg -i "$1" -loglevel quiet  -an -vcodec copy /tmp/cover.jpg

    notify-send -i /tmp/cover.jpg "$(mpc --format '%title%\n%artist%' current)"

    rm /tmp/cover.jpg
fi

