#!/bin/bash
fname=`ncmpcpp --quiet --current-song "%f"`
file=`find /home/kenzie/Music -name "$fname"`

ffmpeg -i "$file" -loglevel quiet  -an -vcodec copy cover.jpg

notify-send -i ~/.dotfiles/cover.jpg "Now Playing" "$(mpc --format '%title% \n%artist% - %album%' current)"

rm cover.jpg
